// <auto-generated />
using EFCoreDemo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDemo.Migrations
{
    [DbContext(typeof(EShopDBContext))]
    [Migration("20250130072958_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreDemo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grocery"
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Smartphone",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Headphones",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Smartwatch",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Tablet",
                            Price = 200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Camera",
                            Price = 350m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Drone",
                            Price = 400m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Bluetooth Speaker",
                            Price = 60m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Name = "Keyboard",
                            Price = 30m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Name = "Mouse",
                            Price = 20m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "T-Shirt",
                            Price = 10m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Jeans",
                            Price = 25m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Jacket",
                            Price = 40m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Shoes",
                            Price = 50m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Sweater",
                            Price = 30m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Hat",
                            Price = 15m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Name = "Socks",
                            Price = 5m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Name = "Scarf",
                            Price = 12m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Name = "Shorts",
                            Price = 20m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Name = "Gloves",
                            Price = 18m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Name = "Rice",
                            Price = 5m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Name = "Wheat Flour",
                            Price = 3m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Name = "Sugar",
                            Price = 2m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Name = "Salt",
                            Price = 1m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Name = "Cooking Oil",
                            Price = 6m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Name = "Milk",
                            Price = 6m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Name = "Eggs",
                            Price = 2m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Name = "Butter",
                            Price = 4m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Name = "Cheese",
                            Price = 5m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Name = "Potatoes",
                            Price = 3m
                        });
                });

            modelBuilder.Entity("EFCoreDemo.Models.Product", b =>
                {
                    b.HasOne("EFCoreDemo.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
